# Generated by Django 5.0.1 on 2024-01-24 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_consultation_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='updated_at',
            new_name='time',
        ),
    ]
